POST http://localhost:8080/webhook
Content-Type: application/json

{
  "token": "Jhj5dZrVaK7ZwHHjRyZWjbDl",
  "challenge": "3eZbrw1aBm2rZgRNFdxV2595E9CY3gmdALWMmHkvFXO7tYXAYM8P",
  "type": "url_verification"
}

###

POST http://localhost:8080/webhook
Content-Type: application/json

{"token":"nh0Gi9IRbW7aGLxRwdQJ0917","team_id":"TSSBG6LP6","api_app_id":"ASV1PSSLE","event":{"client_msg_id":"fac60cef-47c1-4bfe-b301-484ef673a94f","type":"message","text":"eferfe","user":"USGJZCDG9","ts":"1579271025.001200","team":"TSSBG6LP6","blocks":[{"type":"rich_text","block_id":"Mp2LQ","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"eferfe"}]}]}],"channel":"CSE1TGNRG","event_ts":"1579271025.001200","channel_type":"channel"},"type":"event_callback","event_id":"EvSGRGNZQ9","event_time":1579271025,"authed_users":["USE6EHU90"]}

###